[#subscribing-resources-as-subscription-administrator]
= Subscribing resources as subscription administrator

By default, when subscription deploys subscribed applications to target clusters, the applications are deployed into
the subscription's namespace even if the application resources are associated with other namespaces. Also, if an application
resource already exists in the cluster and not created by the subscription, the subscription cannot apply the resource
on top of the existing resource to modify. When you create a subscription as a subscription administrator, these default 
behaviors can be changed.

[#granting-users-and-groups-subscription-admin-privilege]
==Granting users and groups subscription admin privilege

*Required access:* Cluster administrator

. From the console, log in to your hub cluster.

. Create one or more users. 

+
These users represent administrators for the `app.open-cluster-management.io/subscription` application. With OpenShift Container Platform, you can group these users to represent a subscription administrative group, which is demonstrated later in this topic.

. From the terminal, log in to your Red Hat Advanced Cluster Management hub cluster again.

. Add the following subjects into `open-cluster-management:subscription-admin` ClusterRoleBinding with the following command:
+
----
oc edit clusterrolebinding open-cluster-management:subscription-admin
----
+
*Note:* `open-cluster-management:subscription-admin` ClusterRoleBinding has no subject initially.
+
Your subjects might display as the following example:
+
----
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: example-name
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: example-group-name
----

[#namespace-example]
==Application namespace example

*Applicable channel types:* Git

In this example, you are logged in as a subscription administrator and create a subscription to subscribe the sample resource YAML file from a Git repository. The example file contains subscriptions that are located within the following different namespaces:

* Configmap `test-configmap-1` gets created in `multins` namespace. 

* Configmap `test-configmap-2` gets created in `default` namespace.

* Configmap `test-configmap-3` gets created in the `subscription` namespace.
+
----
---
apiVersion: v1
kind: Namespace
metadata:
  name: multins
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-1
  namespace: multins
data:
  path: resource1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-2
  namespace: default
data:
  path: resource2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-3
data:
  path: resource3
----

If the subscription was created by other users, all these config maps get created in the same namespace as the subscription.


[#resource-overwrite-example]
==Resource overwrite example

*Applicable channel types:* Git, ObjectBucket

In this example, the following configmap already exists in the target cluster. 

+
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-1
  namespace: sub-ns
data:
  name: bob
  age: 19
----

You want to subscribe the following sample resource YAML file from a Git repository and `replace` the existing configmap. 

+
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-1
  namespace: sub-ns
data:
  age: 20
----

You log in as a subscription administrator and create a subscription with `apps.open-cluster-management.io/reconcile-option: replace` annotation. For example,

+
----
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: subscription-example
  namespace: sub-ns
  annotations:
    apps.open-cluster-management.io/git-path: sample-resources
    apps.open-cluster-management.io/reconcile-option: replace
spec:
  channel: channel-ns/somechannel
  placement:
    placementRef:
      name: dev-clusters
----

When this subscription is created by a subscription administrator and subscribes the configmap resource, the existing configmap will be replaced to be

+
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-1
  namespace: sub-ns
data:
  age: 20
----

If you want to subscribe the following sample resource YAML file from a Git repository and `merge` with the existing configmap, 
use `apps.open-cluster-management.io/reconcile-option: merge` annotation. For example, 

+
----
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: subscription-example
  namespace: sub-ns
  annotations:
    apps.open-cluster-management.io/git-path: sample-resources
    apps.open-cluster-management.io/reconcile-option: merge
spec:
  channel: channel-ns/somechannel
  placement:
    placementRef:
      name: dev-clusters
----

When this subscription is created by a subscription administrator and subscribes the configmap resource, the existing configmap will be merged to be

+
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-1
  namespace: sub-ns
data:
  name: bob
  age: 20
----

When `merge` option is used, entries from subscribed resource are either created or updated in the existing resource. No entry is removed from the existing resource.

*Important:* If the exising resource you want to overwrite with a subscription is automatically reconciled by other operator or controller, the resource configuration
will be updated by both subscription and the controller or operator. Do not use this method in this case.